[package]
name = "labello-api"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum.workspace = true
labello-client = { path = "../labello-client" }
labello-domain = { path = "../labello-domain" }
labello-storage = { path = "../labello-storage" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding.workspace = true

[dev-dependencies]
tower.workspace = true
tempfile.workspace = true
