[package]
name = "labello-server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
labello-api = { path = "../../crates/labello-api" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
